### ISSUE TITLE
Could not pass event PlayerLoginEvent to VelocityGuard v1.0

### ISSUE THREAD

**Issue by prototype464** [orion-tran/VelocityGuard#1]
Airplane #55 (1.17.1) on Java 16
This error is displayed in console upon a player joining in-game:

[18:38:59 ERROR]: Could not pass event PlayerLoginEvent to VelocityGuard v1.0
java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "us.kunet.velocityguard.backend.PreLoginListener.getProfile" is null
        at us.kunet.velocityguard.backend.PreLoginListener.onPreLogin(VelocityGuardBackendPlugin.java:86) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.17.1.jar:git-Airplane-57]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Airplane-57]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Airplane-57]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Airplane-57]
        at net.minecraft.server.players.PlayerList.attemptLogin(PlayerList.java:770) ~[patched_1.17.1.jar:git-Airplane-57]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:176) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:87) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:546) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:196) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1643) ~[patched_1.17.1.jar:git-Airplane-57]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:482) ~[patched_1.17.1.jar:git-Airplane-57]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1465) ~[patched_1.17.1.jar:git-Airplane-57]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1261) ~[patched_1.17.1.jar:git-Airplane-57]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[patched_1.17.1.jar:git-Airplane-57]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by imkunet** [comment]
As stated in the readme, VelocityGuard is not targeted toward newer game versions. Newer game versions have built in protections for Velocity and should be used instead. Please look into "velocity modern forwarding"
