### ISSUE TITLE
java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.EntityHuman

### ISSUE THREAD

**Issue by prototype464** [orion-tran/VelocityGuard#2]
Airplane #55 (1.17.1) on Java 16
This warning is displayed in console upon booting the server:

[18:56:39 INFO]: [VelocityGuard] Enabling VelocityGuard v1.0*
[18:56:39 WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.EntityHuman
[18:56:39 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:148)
[18:56:39 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105)
[18:56:39 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[18:56:39 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[18:56:39 WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[18:56:39 WARN]:        at us.kunet.velocityguard.backend.PreLoginListener.getEntityHumanClass(VelocityGuardBackendPlugin.java:121)
[18:56:39 WARN]:        at us.kunet.velocityguard.backend.PreLoginListener.<clinit>(VelocityGuardBackendPlugin.java:61)
[18:56:39 WARN]:        at us.kunet.velocityguard.backend.VelocityGuardBackendPlugin.onEnable(VelocityGuardBackendPlugin.java:35)
[18:56:39 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[18:56:39 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[18:56:39 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[18:56:39 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:527)
[18:56:39 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:441)
[18:56:39 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:710)
[18:56:39 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:309)
[18:56:39 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1197)
[18:56:39 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[18:56:39 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by imkunet** [comment]
As stated in the readme, VelocityGuard is not targeted toward newer game versions. Newer game versions have built in protections for Velocity and should be used instead. Please look into "velocity modern forwarding"
